# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rozana-site

on:
  push:
    branches:
      - master
      - Azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://rozana.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_4feb4aa6b8b74fe0a2e024b49c7a31be }}
          password: ${{ secrets.AzureAppService_ContainerPassword_985ea02c8d7544fc8e903a272824f9d3 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rozana.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4feb4aa6b8b74fe0a2e024b49c7a31be }}/ghcr.io/rozanasilva/site:${{ github.sha }}
          context: ./jogos
          file: ./jogos/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rozana-site'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_265e38a7ed80476a923bdce10f386f38 }}
          images: 'rozana.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4feb4aa6b8b74fe0a2e024b49c7a31be }}/ghcr.io/rozanasilva/site:${{ github.sha }}'
